name: Code Coverage

on: [pull_request]

jobs:
  base_branch_cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '8' # Set to your required JDK version
          distribution: 'temurin'

      - name: Build the project
        run: ./gradlew build

      - name: Run tests with coverage
        run: ./gradlew test jacocoTestReport

      - name: Upload code coverage for ref branch
        uses: actions/upload-artifact@v3
        with:
          name: ref-lcov.info
          path: build/reports/jacoco/test/jacocoTestReport.csv # Path to your coverage report

  checks:
    runs-on: ubuntu-latest
    needs: base_branch_cov
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Set to your required JDK version
          distribution: 'temurin'

      - name: Download code coverage report from base branch
        uses: actions/download-artifact@v3
        with:
          name: ref-lcov.info

      - name: Build the project
        run: ./gradlew build

      - name: Run tests with coverage
        run: ./gradlew test jacocoTestReport

      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "build/reports/jacoco/test/jacocoTestReport.csv" # Your coverage report
          base-lcov-file: "ref-lcov.info" # Path to the downloaded coverage report
          minimum-ratio: 0 # Set your desired minimum coverage ratio
          send-summary-comment: true
          show-annotations: "warning" # Possible options warning|error
