name: CI

on:
  pull_request:
    branches:
      - kumari_1  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew clean test jacocoTestReport

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v3  # Updated to use v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html  # Adjust if your path is different
